### ISSUE TITLE
Api should handle the case when Teacher's profile ids are not found

### ISSUE THREAD

**Issue by d4n1elchen** [toolbuddy/NCKU-CSIE-Website#39]
If you input a non-exist id, the `get-teacher-profile` module will crash without error handling, then the server will get down. I deal with this problem by `try ... catch` block in `announcement`'s api. I think it should work for `teacher` as well.

See: https://github.com/team6612/NCKU-CSIE-Website/blob/feature-announcement/apis/announcement.js#L29

**Comment by kaeteyaruyo** [comment]
Done :D
